language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install nose coverage python-coveralls
script:
    - nosetests --with-coverage --cover-branch --cover-package=.
after_success:
  - coveralls
